linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - godot
    - goheader
    - goimports
    - mnd
    - gosec
    - misspell
    - nakedret
    - nestif
    - noctx
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude:
    - "composite literal uses unkeyed fields"
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - unparam
        - bodyclose
