name: project-sprint-2
services:
  postgres-project-sprint-2:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    #   Set a volume for data and initial sql script
    #   May configure initial db for future demo
    volumes:
      - "pgdata-project-sprint-2:/var/lib/postgresql/data"
      # - ./init:/docker-entrypoint-initdb.d/
    command: [ "postgres", "-c", "log_statement=all", "-c", "max_connections=200" ]

volumes:
  pgdata-project-sprint-2: